Getting started with drafts
greenpress/drafts-service pull request #2
Opened 2020-10-01 15:27 UTC by itays123

Things to note:
- In package.json, I wrote @davidmeirlevy as the author
- I added both the authentication service and content service as dependencies
- I set the port for this service to be 9004

2020-10-01 15:29 UTC, itays123 commented
@davidmeirlevy who do you think should work on this branch with me?

2020-10-01 16:01 UTC, davidmeirlevy requested changes
1. where is the index.js?
2. try to use the initials from mailing-service..  and TS instead of JS.

2020-10-01 17:46 UTC, itays123 commented on README.md
> +- [Content-service](https://github.com/greenpress/content-service)
That depends on the question if you want to automate the process of using drafts by proving a `saveAsPost()`, `saveAsMenu()` static methods on the schema. But since it will make the process complicated let's do what you said.

2020-10-01 17:46 UTC, itays123 commented on config/index.js
> +  port: process.env.PORT || 9004,
9005 it is

2020-10-01 17:47 UTC, itays123 commented on config/index.js
> +  port: process.env.PORT || 9004,
we need to document it somewhere

2020-10-01 18:46 UTC, davidmeirlevy commented on config/index.js
> +  port: process.env.PORT || 9004,
We have docs:)

2020-10-01 18:53 UTC, davidmeirlevy commented on server/routes/drafts.ts
> +  app.get("/api/drafts", /* AUTH? */ getDraftsList);
There’s a middleware in api-kit that verify the user..

2020-10-01 18:53 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +export async function getDraftsList(req, res) {
The major issue of draft is to get /set a draft by contextType and Id.
All the rest are minor.

2020-10-01 18:53 UTC, davidmeirlevy commented on .gitignore
> +node_modules
Add:
.vscode
.idea
*.log

2020-10-03 07:10 UTC, davidmeirlevy requested changes
Let the user set whatever he wants on the draft.. it's a service for editors only.

2020-10-03 07:10 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    const { draftId, contextType } = req.params;
get all from req.body

2020-10-03 07:10 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    if (!draftId || draftId === "new") {
Just put all data from req.body and add the tenant and user..
Let the frontend decide what to send.

2020-10-03 07:10 UTC, davidmeirlevy commented on server/middleware/auth-check.ts
> +const authService = require("@greenpress/api-kit/internal-service").service(
No need for that anymore.
There's a middleware at api-kit that populates the user.

2020-10-03 11:54 UTC, itays123 commented on server/middleware/auth-check.ts
> +const authService = require("@greenpress/api-kit/internal-service").service(
thanks for letting me know

2020-10-03 14:00 UTC, davidmeirlevy requested changes

2020-10-03 14:00 UTC, davidmeirlevy commented on server/routes/drafts.ts
> +    .get("/api/drafts/all/:draftId", populateUser, verifyUser, getDraft)
All?

2020-10-03 18:52 UTC, itays123 commented on server/controllers/drafts.ts
> +  type Query = { _id: string; contextType?: string; user: string };
I like using types instead of interfaces when working with middleware functions because it's only used once. for multiple usages I always use interfaces.

2020-10-03 19:11 UTC, itays123 commented on server/controllers/drafts.ts
> +    if (!draftId) {
is it a thing? I'm working with mongo for a while and I never saw a usage of it.
a quick google search let me to this [stackoverflow](https://stackoverflow.com/questions/33305623/mongoose-create-document-if-not-exists-otherwise-update-return-document-in?rq=1), suggesting this solution:

```js
let query = { /* query */ };
let update = {expire: new Date()};
let options = {upsert: true, new: true, setDefaultsOnInsert: true};
let model = await Model.findOneAndUpdate(query, update, options);
```

2020-10-04 10:45 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    if (!draftId) {
Yes.. if the document isn't exist, it will create it from the query + the changes.

2020-10-04 10:46 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +  type Query = { _id: string; contextType?: string; user: string };
Yes, but it's better to define this type outside of the function.. on the global scope of the file.

2020-10-04 10:50 UTC, davidmeirlevy requested changes

2020-10-04 10:50 UTC, davidmeirlevy commented on server/routes/drafts.ts
> +    .get("/api/drafts/:draftId", populateUser, verifyUser, getDraft)
This will probably never be used

2020-10-04 10:50 UTC, davidmeirlevy commented on server/routes/drafts.ts
> +    .put("/api/drafts/:draftId", populateUser, verifyUser, setDraft);
Use will always use set.. if the document already exists it will change the existing, otherwise it will create new.

2020-10-04 11:52 UTC, itays123 commented
one thing I'm still not sure about is the setDraft query variable.
If the id exists, it will work just fine.
but if not, it will return an empty query (`{}`), and will update all of the records!

if we do something like this: `{ _id: undefined }` this will cause trouble during the mongoose search.
@davidmeirlevy any ideas how to combat this?

2020-10-04 11:55 UTC, itays123 commented
do we need a delete route? when will we know how to call it?

2020-10-04 12:36 UTC, davidmeirlevy commented
Yes we do, delete by context and context ID..
The ID of the actual document is not relevant for the frontend that uses this service, not for creation, not for editing and not for deleting.

2020-10-04 13:24 UTC, itays123 commented
only one thing left to do now: the set query

2020-10-04 17:16 UTC, davidmeirlevy requested changes

2020-10-04 17:16 UTC, davidmeirlevy commented on server/routes/drafts.ts
> +export default (app) => {
Populate user, verify user, and also should verify editor, is a must for all endpoints in this service.
You can define it under app.use() before all routes.

2020-10-04 17:16 UTC, davidmeirlevy commented on server/routes/drafts.ts
> +      "/api/drafts/:contextType/:contextId",
Get context type and Id on query params. Not params.

2020-10-04 17:16 UTC, davidmeirlevy commented on server/routes/drafts.ts
> +    .put("/api/drafts/", populateUser, verifyUser, setDraft)
Remove ending slash

2020-10-04 17:16 UTC, davidmeirlevy commented on server/models/draft.ts
> +  contextId: string | undefined;
String or null

2020-10-04 17:16 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +type GetDraftQuery = { contextId: string; contextType: string; user: string };
Context id should be string or null

2020-10-04 17:16 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    const drafts = await Draft.find();
Not all drafts, but only drafts of tenant and user.

2020-10-04 17:16 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    const { contextType, contextId } = req.params;
Should come from req.query and not params.

2020-10-04 17:16 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    const draft = await Draft.findOne(query);
Add .lean() at the end for faster loading.

2020-10-04 17:16 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    const { contextType, contextId = null } = req.query;
All this data should come inside req.body.

2020-10-04 17:16 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    });
Add lean().

2020-10-04 17:16 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +      { contextType, contextId },
Add tenant to query.

2020-10-04 17:16 UTC, davidmeirlevy commented on server/controllers/drafts.ts
> +    const { contextType, contextId } = req.params;
All variables from req.query and not params.

Also, default for contextId should be null (if not exists).

2020-10-04 17:16 UTC, davidmeirlevy commented on server/models/draft.ts
> +    type: String,
Two types: string or null.
Or use validate function.

2020-10-07 10:31 UTC, itays123 commented on server/controllers/drafts.ts
> +    const { contextType, contextId } = req.params;
oh, I thought you meant that I should do it in the setDraft function

2020-10-07 10:43 UTC, itays123 commented on server/models/draft.ts
> +    type: String,
doesn't `required: false` do the trick here?

2020-10-07 13:45 UTC, davidmeirlevy approved these changes
I hope you tested it :)

2020-10-07 13:45 UTC, merged